---
language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.7
  - 3.0
env:
  - DB=mysql
gemfile:
  - gemfiles/rails60-mysql04.gemfile
  - gemfiles/rails61-mysql05.gemfile
services:
  - mysql
before_install: gem install bundler -v 2.1.4
